# Generated by Django 5.0.6 on 2024-08-02 10:37

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
            options={
                'verbose_name': 'author-book relation',
                'verbose_name_plural': 'author-book relations',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('year', models.PositiveIntegerField(validators=[catalog.models.validate_year], verbose_name='release year')),
                ('author', models.ManyToManyField(blank=True, through='catalog.AuthorBook', to='catalog.author', verbose_name='authors')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
        migrations.AlterUniqueTogether(
            name='authorbook',
            unique_together={('author', 'book')},
        ),
    ]
