# Generated by Django 5.0.7 on 2024-08-02 13:48

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_authorbook_book_authorbook_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(validators=[catalog.models.validate_date_of_birth]),
        ),
    ]
