# Generated by Django 5.0.7 on 2024-08-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_author_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='authorbook',
            options={'ordering': ['id'], 'verbose_name': 'author-book relation', 'verbose_name_plural': 'author-book relations'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
