# Generated by Django 5.0.7 on 2024-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options_alter_authorbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='catalog.author'),
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
    ]
